### ISSUE TITLE
ส่วนที่ 2 ข้อมูลการเลี้ยงและสถานภาพฟาร์ม

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#100]
อาจารย์คะ หนูขอเปลี่ยนแปลงข้อมูลในส่วนที่ 2 เป็นลักษณะนี้ได้ไหมคะ เพราะจะได้สะดวกในการกรอกข้อมูลอ่ะค่ะ
![image](https://cloud.githubusercontent.com/assets/20829708/21768038/fd555706-d6a9-11e6-84f8-971b9f5eb4e6.png)
![image](https://cloud.githubusercontent.com/assets/20829708/21768066/345c5a7e-d6aa-11e6-9e20-b62b7e378338.png)
![image](https://cloud.githubusercontent.com/assets/20829708/21768096/64f5b7d4-d6aa-11e6-9592-4a069e6b0125.png)
![image](https://cloud.githubusercontent.com/assets/20829708/21768116/84b579c4-d6aa-11e6-88bc-10ecd47bb5c7.png)
![image](https://cloud.githubusercontent.com/assets/20829708/21768132/97b838ea-d6aa-11e6-852e-02ea00343638.png)
![image](https://cloud.githubusercontent.com/assets/20829708/21768151/b00bbc8c-d6aa-11e6-9257-a1cfb48ab822.png)

**Comment by pchaow** [comment]
คือถ้าเปลี่ยนข้อมูลเก่า มันจะต้องมาแก้ไขให้เข้ากับตัวเลือกครับ
แล้ว ปัญหาก็คือ วัวพันธุ์ต่างๆ ราคามันไม่ท่ากัน และแหล่งที่มาของพันธ์วัวก็อาจจะไม่เหมือนกันครับ

**Comment by pchaow** [comment]
แนะนำว่าถ้าอยากแก้ไขให้เป็นตัวเลือก จากแบบเดิมส่วนของแหล่งที่มาและราคาสามารถเปลี่ยนเป็นตัวเลือกได้ แบบนี้จะดีกว่า แต่ถ้าอยากได้ checkbox มันจะกินเนื้อที่ และข้อมูลของแหล่งที่มาของวัวแต่ละพันธุ์จะไม่สามารถเก็บได้เหมือนเดิม
![image](https://cloud.githubusercontent.com/assets/5770600/21769058/68292918-d6af-11e6-9799-5d6e7ce825e3.png)

ถ้ายังไงโทรคุยได้นะครับ ในรายละเอียด

**Comment by wiranut** [comment]
อาจารย์ว่างไหมคะ วันนี้ตอนบ่ายโมง อยากจะเข้าไปคุยรายละเอียดเพิ่มเติมค่ะ

**Comment by pchaow** [comment]
สรุปจะเปลี่ยนแหล่งที่มาเป็น select-option

**Comment by pchaow** [comment]
ตอนนีระบบอัพเดทเรียบร้อยแล้วเป็นแบบนี้ นะครับ หากเจอข้อผิดพลาดของโปรแกรมก็สามารถแจ้งให้แก้ได้นะครับ
![image](https://cloud.githubusercontent.com/assets/5770600/24438056/feea87fa-146e-11e7-84b4-7cfdb6339400.png)
