### ISSUE TITLE
cattle management information system

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#102]
อาจารย์คะ ในส่วนของบันทึกข้อมูลเกษตรกรใหม่ ระบบมีปัญหา

**Comment by wiranut** [comment]
![image](https://user-images.githubusercontent.com/20829708/27781444-145a31b0-5ff8-11e7-90a4-f95d96f75c87.png)

**Comment by wiranut** [comment]
![image](https://user-images.githubusercontent.com/20829708/27781637-04e0d526-5ff9-11e7-9615-7f5a2977ea70.png)
อาจารย์ข้อมูลมีปัญหาทุกส่วน ในแบบฟอร์มกรอกข้อมูลของเกษตรกรใหม่ ที่เป็นตัวเลือกไม่สามารถเลือกได้ค่ะ

**Comment by chontipan** [comment]
ขอบใจมากครับ พรุ่งนี้ดูให้นะครับ

**Comment by pchaow** [comment]
แก้เรียบร้อยละครับ เดี๋ยวทดสอบดูนะครับ
![image](https://user-images.githubusercontent.com/5770600/27790684-c264fee8-601b-11e7-83e5-cf460e675bd4.png)

**Comment by pchaow** [comment]
ตอนเพิ่มก็แก้ละ
![image](https://user-images.githubusercontent.com/5770600/27790704-d99c4ff8-601b-11e7-9cfe-fb88deb1661e.png)

**Comment by wiranut** [comment]
ขอบคุณค่ะอาจารย์

**Comment by wiranut** [comment]
ขอบคุณค่ะอาจารย์
