### ISSUE TITLE
คลิ๊กตรงรูปจังหวัดกับอำเภอตรงแผนที่แล้วขึ้น 404

### ISSUE THREAD

**Issue by chontipan** [pchaow/cattlemis#103]
![image](https://user-images.githubusercontent.com/9138402/27788573-67b8f506-6013-11e7-87f7-25c469c0eafb.png)

![image](https://user-images.githubusercontent.com/9138402/27788581-6bf6ade8-6013-11e7-9247-d61cd016baf5.png)

**Comment by pchaow** [comment]
แก้เรียบร้อยละ
