### ISSUE TITLE
ไฟล์แบบสอบถามเกษตรกรผู้เลี้ยงโคเนื้อ 4 จังหวัด พะเยา เชียงราย แพร่ น่าน

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#104]
อาจารย์คะ อันนี้เป็นไฟล์แบบสอบถาม ที่จะให้อาจารย์อัพขึ้นระบบค่ะ
[แบบสอบถาม-23-05-2016-แก้ไข-28-9-2016.pdf](https://github.com/pchaow/cattlemis/files/1292598/-23-05-2016-.-28-9-2016.pdf)

**Comment by pchaow** [comment]
อัพโหลดเรียบร้อยละคับ
