### ISSUE TITLE
3.6 หญ้าชนิดอะไร เอาออก

### ISSUE THREAD

**Issue by chontipan** [pchaow/cattlemis#14]

**Comment by pchaow** [comment]
please fix databases and it's migration

**Comment by pchaow** [comment]
โอเค เอาชนิดหญ้ากลับมาละ ตอนแรกหาย
![image](https://cloud.githubusercontent.com/assets/5770600/17280773/0bb3f2a4-57bf-11e6-9032-3ffbe7c997d9.png)
