### ISSUE TITLE
ส่วนที่ 4 ในข้อ 4.8 การจัดการมูลโคในฟาร์ม

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#20]
พอเข้าไปแก้ไขในส่วนของข้อมูลที่กรอกไปแล้ว แต่ไม่บันทึกข้อมูลให้ 
**แต่กรอกข้อมูลใหม่ไม่มีปัญหา บันทึกข้อมูลได้ตามปกติค่ะ

**Comment by pchaow** [comment]
ตอนนี้ดูให้แล้วครับ เดี๋ยวจะอัพเดทขึ้น server ให้

**Comment by pchaow** [comment]
fix at https://github.com/pchaow/cattlemis/commit/e28f32b299f9c4938759734db92fe58430a385e4

**Comment by wiranut** [comment]
ขอบคุณค่ะอาจารย์
