### ISSUE TITLE
ส่วนที่ 6.5 กลุ่มวิสาหกิจชุมชนและสหกรณ์โคเนื้อ

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#22]
อาจารย์คะตรงที่   เข้าร่วมเมื่อ....... เป็นพิมพ์เองได้ไหมคะ แต่ตอนนี้ยังเป็นปฏิทินอยู่อ่ะค่ะ

**Comment by pchaow** [comment]
แก้แล้วนะครับ รอสักครู่จะอัพเดท
![image](https://cloud.githubusercontent.com/assets/5770600/17390513/e85f0458-5a37-11e6-934e-9cc026535081.png)

**Comment by wiranut** [comment]
ขอบคุณค่ะ
