### ISSUE TITLE
ส่วนข้อมูล 2-3 แท่ง ให้เป็น pie chart

### ISSUE THREAD

**Issue by chontipan** [pchaow/cattlemis#25]

**Comment by chontipan** [comment]
ทำให้ data label ออกมายังไม่ได้

**Comment by pchaow** [comment]
อันนี้ไม่ต้องทำละครับ เนื่องด้วยถ้าเราฟิลเตอร์ข้อมูลบางจังหวัดอาจทำให้ได้แผนภาพไม่ตรงกัน
ปิดจนกว่าจะ ยืนยันกับ อ.แป้นว่าจะเลือกหนทางใด
