### ISSUE TITLE
กราฟ ดูเป็นรายจังหวัด/อำเภอ

### ISSUE THREAD

**Issue by chontipan** [pchaow/cattlemis#27]

**Comment by pchaow** [comment]
ต้องรอวาดแผนที่

**Comment by pchaow** [comment]
เพิ่มแผนที่ใน normal-chart ละ https://github.com/pchaow/cattlemis/commit/9c575858ea0b740af643d627b28227c048ff1a11

![image](https://cloud.githubusercontent.com/assets/5770600/17425511/47807f3c-5af8-11e6-90ef-ff3aadcc49e4.png)

**Comment by pchaow** [comment]
แก้ไขสำหรับ สถานภาพการระบาดของโรคในฟาร์ม
-  https://github.com/pchaow/cattlemis/commit/72b10f4b81ffe4f6c74fd277398ef98369d63c58

**Comment by pchaow** [comment]
เสร็จครบทุกแบบแล้ว
