### ISSUE TITLE
ใช่/ไม่ใช่ radio button

### ISSUE THREAD

**Issue by chontipan** [pchaow/cattlemis#32]

**Comment by pchaow** [comment]
อัพเดท radio-button ในข้อ 2.15 - https://github.com/pchaow/cattlemis/commit/f772f317aca633446ecbb84737f97fa46cd40c39
![image](https://cloud.githubusercontent.com/assets/5770600/17425054/82208d62-5af3-11e6-95a1-d938d90fb585.png)
