### ISSUE TITLE
ส่วนที่ 7 การได้รับบริการ การส่งเสริมและสนับสนุนจากหน่วยงานต่าง ๆ ในข้อ 7.1 

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#35]
อาจารย์คะ ข้อมูลในส่วนของ 7.1 หายไปหนึ่งตัวเลือกค่ะ คำที่หายคือ ..... กรมส่งเสริมการเกษตร ค่ะ

**Comment by chontipan** [comment]
ดำเนินการแก้ไขละครับ รออัพเดทสักครู่

**Comment by pchaow** [comment]
แก้เรียบร้อยละ ลองดูนะครับ ติดปัญหา เปิด issue ได้ทันทีคับ

![image](https://cloud.githubusercontent.com/assets/5770600/17403855/ae3c11e8-5a83-11e6-8a7c-969a58dc92b1.png)

https://github.com/pchaow/cattlemis/commit/4c8cbb3d630169eb24558f9fcdfe1bce4cf0b011

**Comment by wiranut** [comment]
ขอบคุณค่ะ
