### ISSUE TITLE
แผนภูมิรายงานอายุ

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#59]
![image](https://cloud.githubusercontent.com/assets/20829708/17663897/5478d1a6-631a-11e6-95fd-b6ac0e736e5f.png)
อาจารย์คะ ในข้อมูลที่กรอกไม่มีอายุน้อยกว่า 15 และ 15-21  ทำไมถึงปรากฎในแผนภูมิรายงานอายุคะ

**Comment by wiranut** [comment]
อาจารย์คะ อายุในช่วง 15-21 มี 1 คนถูกต้องแล้วค่ะ แต่มีปัญหาตรงช่วงอายุน้อยกว่า 15 อย่างเดียวค่ะ

**Comment by pchaow** [comment]
มีคนนึงใส่ 0 ครับ เดี๋ยวถ้าหาได้ว่าเป็นใครแล้วจะบอกนะครับ

**Comment by wiranut** [comment]
ขอบคุณค่ะ

**Comment by pchaow** [comment]
![image](https://cloud.githubusercontent.com/assets/5770600/17688565/94831c9e-63aa-11e6-875f-feffdf756766.png)
อันนี้เป็นข้อมูลจากฐานข้อมูลจริงครับ ลองตรวจสอบจาก id และชื่อดูก่อน แล้วก็ตรวจสอบกับ ในแบบสอบถามว่าทางเกษตรกรได้กรอกไว้หรือไม่ครับ ถ้าไม่ได้กรอก ผมจะ filter ออกจากกราฟให้ครับ

**Comment by wiranut** [comment]
ไม่ได้กรอกค่ะ

**Comment by pchaow** [comment]
โอเค ถ้างั้นผมจะ filter คนที่มีอายุเป็น 0 ออกนะ

**Comment by pchaow** [comment]
![image](https://cloud.githubusercontent.com/assets/5770600/17699445/e30b0a44-63ea-11e6-91ff-1faf70e1ca72.png)

**Comment by wiranut** [comment]
ค่ะ
