### ISSUE TITLE
แผนภูมิลักษณะการเลี้ยงโคเนื้อ

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#61]
![image](https://cloud.githubusercontent.com/assets/20829708/17725586/b77af0ce-6476-11e6-89f3-66406b6f39e0.png)
อาจารย์คะช่วยเปลี่ยนเป็น pie chart ได้ไหมคะ

**Comment by chontipan** [comment]
กำลังดำเนินการแก้ไข รอสักครู่นะครับ

**Comment by wiranut** [comment]
ขอบคุณค่ะ
