### ISSUE TITLE
5.2 แหล่งเงินทุนกู้ยืม

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#63]
![image](https://cloud.githubusercontent.com/assets/20829708/17830019/60724da6-66ea-11e6-975a-609503f434d0.png)
อาจารย์คะ ตรงเงินกู้จากธนาคารพาณิชย์ ให้มี(ระบุธนาคาร) ด้วยได้ไหมคะ

**Comment by pchaow** [comment]
โอเคคับ เดี๋ยวขอดูก่อนนะคับ

**Comment by wiranut** [comment]
ขอบคุณค่ะ

**Comment by pchaow** [comment]
ตอนนี้แก้ไขให้แล้วครับ
