### ISSUE TITLE
4.8 การจัดการมูลโคในฟาร์ม

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#64]
![image](https://cloud.githubusercontent.com/assets/20829708/17836460/b2894440-67bd-11e6-8a71-1e98de4f5ed6.png)
อาจารย์คะ คลิกเลือกไปแลัว แต่ไม่บันทึกข้อมูลให้คะ

**Comment by chontipan** [comment]
รับทราบครับ เดี๋ยวดูให้นะครับ

**Comment by chontipan** [comment]
ขอเบอร์โทรศัพท์เราได้ไหมครับ พอดีผมอลองของผมแล้วบันทึกผลได้ อยากจะสอบถามว่าที่เราบันทึกไม่ได้คือสถานการณ์แบบใด

**Comment by pchaow** [comment]
อยากรู้ว่า ตอนนี้เซฟ ไม่ได้ทุกคนเลย หรือไม่คนเดียวครับที่มีปัญหา

**Comment by wiranut** [comment]
บางอันก็ไม่บันทึกให้ ไม่รู้ว่าเป็นเพราะเน็ตหรือว่าระบบอ่ะค่ะ

**Comment by wiranut** [comment]
เบอร์โทร 0821889156 (วีรนุช) ค่ะ
