### ISSUE TITLE
3.7 อาหารที่ใช้เลี้ยงโคเนื้อ

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#71]
![image](https://cloud.githubusercontent.com/assets/20829708/17959120/7f8a123c-6ac8-11e6-8490-57c347bde03d.png)
อาจารย์คะ ของ......นายอุดมเขตต์ เดชะบุญ บันทึกขัอมูลตรงนี้ไม่ได้ค่ะ

**Comment by pchaow** [comment]
โอเคครับ ตอนนี้น่าจะเซฟได้ละครับ ถ้าเซฟไม่ได้อีก เปิด issue ใหม่เลยนะครับตอนนี้ผมทำให้เซฟได้ละ
