### ISSUE TITLE
3.3 ลักษณะการเลี้ยงโค

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#72]
![image](https://cloud.githubusercontent.com/assets/20829708/17960467/6e4a3918-6ad0-11e6-93ed-172210b450d1.png)
นายคงเดช วงเวียน บันทึกข้อมูลตรงนี้ไม่ได้ค่ะ

**Comment by pchaow** [comment]
ผมอัพเดทได้อ่ะครับ ยังไงลองตรวจสอบดูนะครับ ว่านายคงเดช เขาเลือกอะไร
อาจจะเป็นเพราะ internet มีปัญหาก็ได้ครับ
![screenshot from 2016-08-26 20-11-47](https://cloud.githubusercontent.com/assets/5770600/18006361/5df93254-6bc9-11e6-8e9c-f68c561927e4.png)

**Comment by pchaow** [comment]
โอเคครับ ตอนนี้พอจับเค้าลางปัญหาได้ละ เดี๋ยวจะแก้ให้หมดเลยทีเดียว

**Comment by pchaow** [comment]
โอเคครับ ตอนนี้น่าจะเซฟได้ละครับ ถ้าเซฟไม่ได้อีก เปิด issue ใหม่เลยนะครับตอนนี้ผมทำให้เซฟได้ละ

**Comment by pchaow** [comment]
ปัญหาเกิดจากความไม่ consistency ของชุดคำสั่ง ซึ่งเกิดจากฟังก์ชั่นนี้

```
private function generateManyChoices(Request $request, $form, $choices, $field)
    {
        if ($request->has("$field")) {
            $fields = $request->get("$field");
            foreach ($fields as $item) {
                if (isset($item['pivot'])) {
                    $pivot = $item['pivot'];
                    $choices[$item['id']] = $pivot;
                } else {
                    $choices[] = $item['id'];
                }
            }
        }
        return $choices;
    }
```

ซึ่งในส่วน $choices[] = $item['id'] ทำให้เกิดการทับกันของ choices ที่จะส่งข้อมูลไปยังฐานข้อมูลได้ โดยแก้เป็น

```
private function generateManyChoices(Request $request, $form, $choices, $field)
    {

        if ($request->has("$field")) {

            $fields = $request->get("$field");

            foreach ($fields as $item) {

                if (isset($item['pivot'])) {
                    $pivot = $item['pivot'];
                    $choices[$item['id']] = $pivot;
                } else {
                    $choices[$item['id']] = [];
                }
            }
        }
        return $choices;
    }
```

**Comment by chontipan** [comment]
ขอบคุณครับ

**Comment by wiranut** [comment]
ขอบคุณค่ะอาจารย์
