### ISSUE TITLE
จำนวนเกษตรกรผู้เลี้ยงโคเนื้อ 4 จังหวัดภาคเหนือ

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#74]
![image](https://cloud.githubusercontent.com/assets/20829708/18024918/5c23af40-6c41-11e6-9d2e-86c20a1b4391.png)
อาจารย์คะ จำนวนเกษตรกรของจังหวัดพะเยา เชียงราย กรอกข้อมูลครบแล้ว 100 คน แต่ขึ้นในระบบแค่ 99 คน 
***ส่วนของจังหวัดเชียงราย มี 98 คน แต่ขึ้นในระบบ 97 คน 
อาจารย์ช่วยดูให้หนูหน่อยนะคะ

**Comment by wiranut** [comment]
**\* จังหวัดแพร่ กับ พะเยา ที่กรอกข้อมูลครบ 100 คน แต่ขึ้นในระบบแค่ 99 คน ค่ะ

**Comment by pchaow** [comment]
ลองดูของคุณหล้า แสงสุวรรณครับ ข้อมูลจังหวัดเดิมทีไม่มี แต่ว่าผมเพิ่มไปให้ละ
