### ISSUE TITLE
เช็ค PDF

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#75]
พะเยาครบ 100 คนแล้วค่ะส่วนในจังหวัดแพร่กับเชียงรายกำลังเช็คค่ะ 
***ในส่วนของ PDF ข้อ 3.9 ไม่แสดงผล
 3.11 ซ้ำ
 6.2 และ 6.3 ไม่แสดงผล

**Comment by chontipan** [comment]
รับทราบครับ เดี๋ยวดูให้นะครับ

**Comment by wiranut** [comment]
ขอบคุณค่ะ

**Comment by chontipan** [comment]
แก้ไขแล้ว  รออัพใน server ครับ
