### ISSUE TITLE
ส่วนที่ 8 ปัญหาและอุปสรรค

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#76]
![image](https://cloud.githubusercontent.com/assets/20829708/18026202/75d579be-6c69-11e6-8db0-7853c5e54402.png)
อาจารย์คะ  ข้อความ....ที่ว่า ปัญหาและอุปสรรคในการเลี้ยงโคเนื้อของท่าน ของ 8.1 กับ 8.2 เหมือนกันอ่ะค่ะ

**Comment by chontipan** [comment]
โอเคครับ แก้ไขแล้ว รออัพขึ้น server แปป

![image](https://cloud.githubusercontent.com/assets/9138402/18026336/3df3d64a-6c6d-11e6-93e4-61c3897ade26.png)

**Comment by wiranut** [comment]
ขอบคุณค่ะ
