### ISSUE TITLE
ส่วนที่ 5 แหล่งเงินทุนที่ใช้เลี้ยงโคเนื้อ

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#77]
![image](https://cloud.githubusercontent.com/assets/20829708/18044853/fd4be6b2-6df9-11e6-81cd-06a95a4a735f.png)
อาจารย์คะ ข้อความที่แทรกคำว่า (ผป) เอาออกได้ไหมคะ

**Comment by chontipan** [comment]
รับทราบครับ แก้แปปครับ

**Comment by chontipan** [comment]
แก้ไขเรียบร้อย รออัพบน server ครับ

**Comment by wiranut** [comment]
ขอบคุณค่ะ
