### ISSUE TITLE
ส่วนที่ 6 ข้อมูลการตลาด การรวมกลุ่มของสมาชิก(วิสาหกิจชุมชนและสหกรณ์)

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#78]
![image](https://cloud.githubusercontent.com/assets/20829708/18231203/7398a4c2-72dc-11e6-8574-05048b65db31.png)
อาจารย์คะ ข้อมูล 6.2 และ 6.3 ใน PDF ไฟล์ ไม่แสดงผลให้อ่ะค่ะ

**Comment by chontipan** [comment]
ของคนชื่ออะไรนะครับ

**Comment by chontipan** [comment]
okay ข้อมูลออกละครับ ขออภัยนะ
![image](https://cloud.githubusercontent.com/assets/9138402/18232048/fb17562c-72f1-11e6-9440-a726edf527fc.png)

**Comment by chontipan** [comment]
เดี๋ยวรออัพเดทใน server แปปครับ

**Comment by wiranut** [comment]
ขอบคุณค่ะ
