### ISSUE TITLE
3.4 พื้นที่ถือครองทางการเกษตร

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#79]
![image](https://cloud.githubusercontent.com/assets/20829708/18231318/3f2669e0-72e1-11e6-805b-c4ee25a19b1d.png)
อาจารย์คะ แก้ไขในส่วนของข้อมูลพื้นที่ ให้เป็น จำนวน..............ไร่......................งาน เพิ่มในข้อ 3.4, 3.5, 3.6 ค่ะ

**Comment by chontipan** [comment]
ผมงงนิดๆว่าภาพจะออกมาเป็นยังไง เราลองตัดต่อภาพที่อยากได้มาให้ทีได้ไหมครับ ว่าเติม ไร่ และ งาน ตรงไหน

Best Regards,

Chontipan Plengvittaya
Dept of Software Engineering
School of ICT
University of Phayao
Phayao, Thailand 56000

2016-09-04 20:54 GMT+07:00 Wiranut Thannithi notifications@github.com:

**Comment by wiranut** [comment]
สมมุติว่า มีพื้นที่ถือครอง......1........ ไร่......2....... งาน และมีพื้นที่ในการเลี้ยงโค......1 ....... ไร่ .........2......งาน ประมาณนี้อ่ะค่ะ

**Comment by chontipan** [comment]
ครับผม

**Comment by chontipan** [comment]
แก้ละครับ รออัพเดดใน server
