### ISSUE TITLE
ส่วนที่ 3  ข้อมูลแรงงาน พื้นที่ในการเลี้ยง และการจัดการอาหาร

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#80]
![image](https://cloud.githubusercontent.com/assets/20829708/18232301/fd928eda-72f6-11e6-9a61-1fadf2d202e9.png)
อาจารย์คะใน PDF ไฟล์ ไม่ปรากฎข้อมูลจำนวนไร่ และราคาเช่าที่ดินค่ะ

**Comment by chontipan** [comment]
โอเคครับ ข้อมูลออกละ เดี๋ยวรออัพเดดใน server นะครับ
![image](https://cloud.githubusercontent.com/assets/9138402/18232412/41c78a5e-72f9-11e6-9d4b-6c7d781da31f.png)

**Comment by wiranut** [comment]
ขอบคุณค่ะ
