### ISSUE TITLE
1.3 ที่อยู่ฟาร์ม

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#82]
![image](https://cloud.githubusercontent.com/assets/20829708/18238495/b7b8016c-7367-11e6-9d1b-304eeacead99.png)
อาจารย์คะ เลขที่ตั้งฟาร์ม ใส่ / ไม่ได้อ่ะค่ะ

**Comment by chontipan** [comment]
รับทราบครับ แก้ไขแปปนะครับ

**Comment by chontipan** [comment]
update ใน server แล้วครับ

**Comment by wiranut** [comment]
ขอบคุณค่ะ
