### ISSUE TITLE
1.11 รายได้เฉลี่ยต่อปีของการขายโคเนื้อ 

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#83]
![image](https://cloud.githubusercontent.com/assets/20829708/18241359/d546aaae-737a-11e6-8fbf-aeaf711e4b0b.png)
อาจารย์คะ เพิ่มข้อมูลในส่วนนี้ว่า......... ยังไม่มีการขายโคเนื้อ......... ได้ไหมคะ เพราะว่ามีบางคนยังไม่ได้ขายก็เลยยังไม่มีรายได้ตรงส่วนนี้อ่ะค่ะ

**Comment by chontipan** [comment]
รับทราบครับ ขอแก้ไขพรุ่งนี้นะครับ

**Comment by wiranut** [comment]
ค่ะ

**Comment by pchaow** [comment]
ตอนนี้ใครไม่มีรายได้ ให้ลบข้อมูลออก (ไม่ต้องกรอก 0) นะครับไม่ต้องกรอก เดี๋ยวจะไปแก้ ในกราฟเพิ่มเติมให้ครับ

**Comment by pchaow** [comment]
แก้แบบนี้ไปก่อนครับ เพราะที่เสนอมาไม่สามารถทำได้โดยง่าย มันกระทบหลายส่วนมากครับ

![image](https://cloud.githubusercontent.com/assets/5770600/18395180/a0f25710-76e7-11e6-96d4-a4612f70281e.png)

**Comment by wiranut** [comment]
รับทราบค่ะอาจารย์
