### ISSUE TITLE
เพิ่มส่วนแผนที่

### ISSUE THREAD

**Issue by chontipan** [pchaow/cattlemis#9]

**Comment by pchaow** [comment]
ส่วนแผนที่มีทั้งแบบ รายงาน (ปักหมุด) และอาจจะเป็นส่วนของการเลือก พิกัดฟาร์มของเกษตรกร
ซึ่งตอนแรกพิกัดฟาร์มของเกษตรกร อาจจะใช้จาตำแหน่งของ จังหวัด อำเภอ ตำบล ซึ่งตอนนี้ยังไม่มีข้อมูลในฐานข้อมูล ???

**Comment by pchaow** [comment]
ต้องรอวาดแผนที่

**Comment by pchaow** [comment]
ซ้ำกับ google lat,lng
