### ISSUE TITLE
ทราบถึงว่า ใครเลี้ยงวัวพันธ์ไหนบ้าง

### ISSUE THREAD

**Issue by chontipan** [pchaow/cattlemis#91]

**Comment by pchaow** [comment]
ทำได้แค่ ค้นหาและแสดง ไม่ได้แสดงจำนวนวัวทั้งหมด

![image](https://cloud.githubusercontent.com/assets/5770600/18414679/01eed3ba-77fe-11e6-8b49-76c9eadccf42.png)

![image](https://cloud.githubusercontent.com/assets/5770600/18414678/f5985f14-77fd-11e6-8235-488c65667f25.png)
