### ISSUE TITLE
ข้อมูลระบบการเลี้ยงโคเนื้อ 4 จังหวัด

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#95]
อาจารย์คะ ข้อมูลของเกษตรกรที่กรอกไปแล้ว ไม่สามารถลบได้ รบกวนอาจารย์ช่วยดูให้หน่อยค่ะ

**Comment by pchaow** [comment]
ของคนไหนเหรอครับ

**Comment by pchaow** [comment]
เจอปัญหาละครับ เดี๋ยวกำลังจะแก้ให้ครับ

**Comment by wiranut** [comment]
ขอบคุณค่ะอาจารย์

**Comment by pchaow** [comment]
แก้ไขเรียบร้อยแล้วครับ
(ตอนนี้เป็นการลบแล้ว ข้อมูลจะลบเลย ไม่สามารถกู้คืนได้ครับ ยังไงก็ระมัดระวังด้วย)

**Comment by wiranut** [comment]
ขอบคุณค่ะอาจารย์
