### ISSUE TITLE
แผนภูมิรายงานจำนวนโคเนื้อที่เลี้ยง

### ISSUE THREAD

**Issue by wiranut** [pchaow/cattlemis#97]
![image](https://cloud.githubusercontent.com/assets/20829708/19155922/5efbeca8-8c0a-11e6-8775-38a4e10089da.png)
อาจารย์คะ ข้อความตรงที่...... โคเพศเมียอายุมากกว่า 6 เดือนขึ้นไปแต่ไม่ใช่พ่อพันธุ์คุมฝูง..... เปลี่ยนเป็น...... โคเพศเมียอายุมากกว่า 6 เดือนขึ้นไปแต่ยังไม่ตั้งท้อง รบกวนอาจารย์ดูให้หน่อยนะคะ

**Comment by chontipan** [comment]
รับทราบครับ พรุ่งนี้เดี๋ยวแก้ไขให้นะครับ

**Comment by wiranut** [comment]
ขอบคุณค่ะอาจารย์

**Comment by chontipan** [comment]
แก้ไขแล้วครับผม

**Comment by pchaow** [comment]
![image](https://cloud.githubusercontent.com/assets/5770600/19194611/606dec16-8cd8-11e6-8542-f91694e09be0.png)
